In [1]:
import pandas as pd
import numpy as np

In [4]:
qdf = pd.read_csv('query_dataset.csv')

In [5]:
qdf

query       tag
0  what is the basic distance for free delivery?  delivery
1              how far can you deliver for free?  delivery
2                    is free delivery available?  delivery
3                           what is in the menu?      menu

In [15]:
X  = qdf['query'].tolist()
X

['what is the basic distance for free delivery?',
 'how far can you deliver for free?',
 'is free delivery available?',
 'what is in the menu?']

In [16]:
y = qdf['tag'].tolist()
y

['delivery', 'delivery', 'delivery', 'menu']

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(X)
X.toarray()

array([[0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0]], dtype=int64)

In [20]:
print(vectorizer.get_feature_names())

['available', 'basic', 'can', 'deliver', 'delivery', 'distance', 'far', 'for', 'free', 'how', 'in', 'is', 'menu', 'the', 'what', 'you']


In [21]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
y = lb.fit_transform(y)
y

array([[0],
       [0],
       [0],
       [1]])

In [23]:
print(lb.classes_)

['delivery' 'menu']


In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
model = RandomForestClassifier(random_state=1)
model.fit(X,y) # algorithm with learn to identify tags

RandomForestClassifier(random_state=1)

In [28]:
# testing
text  = 'how far can you deliver for free?'
input_data = vectorizer.transform([text])
input_data.toarray()

array([[0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [30]:
result = model.predict(input_data) # answer

In [34]:
lb.inverse_transform(result)

array(['delivery'], dtype='<U8')

In [43]:
# testing
text  = 'how is the menu?'
input_data = vectorizer.transform([text])
input_data.toarray()
result = model.predict(input_data) # answer
print(lb.inverse_transform(result))

['menu']
