In [59]:
import pandas as pd
import numpy as np

In [60]:
qdf = pd.read_csv('query_dataset.csv')

In [61]:
qdf

query       tag
0   what is the basic distance for free delivery?  delivery
1               how far can you deliver for free?  delivery
2                     is free delivery available?  delivery
3                            what is in the menu?      menu
4                what are the options in the menu      menu
5                                show me the menu      menu
6                              is there any offer    offers
7                what are the offers on the pizza    offers
8                  are discount offers available?    offers
9                              when do you close?    timing
10                              when do you open?    timing
11                          what is closing time?    timing
12                               how do we reach?   address
13                  are you available in lucknow?   address
14                         where are you located?   address
15                            are you open at 9am    timing
16                      is there any pizza combos     combo
17                what is combo offer of the week     combo
18                         available combo offers     combo
19                   are there burgers available?      menu
20                   do you deliver free of cost?  delivery

In [62]:
X  = qdf['query'].tolist()
X

['what is the basic distance for free delivery?',
 'how far can you deliver for free?',
 'is free delivery available?',
 'what is in the menu?',
 'what are the options in the menu',
 'show me the menu',
 'is there any offer',
 'what are the offers on the pizza',
 'are discount offers available?',
 'when do you close?',
 'when do you open?',
 'what is closing time?',
 'how do we reach?',
 'are you available in lucknow?',
 'where are you located?',
 'are you open at 9am',
 'is there any pizza combos',
 'what is combo offer of the week',
 'available combo offers',
 'are there burgers available?',
 'do you deliver free of cost?']

In [63]:
y = qdf['tag'].tolist()
y

['delivery',
 'delivery',
 'delivery',
 'menu',
 'menu',
 'menu',
 'offers',
 'offers',
 'offers',
 'timing',
 'timing',
 'timing',
 'address',
 'address',
 'address',
 'timing',
 'combo',
 'combo',
 'combo',
 'menu',
 'delivery']

In [64]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(X)
print(X.toarray())

[[0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1]
 [0 1 0 0 

In [65]:
print(vectorizer.get_feature_names())

['9am', 'available', 'basic', 'burgers', 'close', 'closing', 'combo', 'combos', 'cost', 'deliver', 'delivery', 'discount', 'distance', 'far', 'free', 'located', 'lucknow', 'menu', 'offer', 'offers', 'open', 'options', 'pizza', 'reach', 'time', 'week']


In [66]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
y = lb.fit_transform(y)
y

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0]])

In [67]:
print(lb.classes_)

['address' 'combo' 'delivery' 'menu' 'offers' 'timing']


In [68]:
from sklearn.ensemble import RandomForestClassifier

In [69]:
model = RandomForestClassifier(random_state=1)
model.fit(X,y) # algorithm with learn to identify tags

RandomForestClassifier(random_state=1)

In [70]:
# testing
text  = 'how far can you deliver for free?'
input_data = vectorizer.transform([text])
print(input_data.toarray())

[[0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]]


In [71]:
result = model.predict(input_data) # answer

In [72]:
lb.inverse_transform(result)

array(['delivery'], dtype='<U8')

In [73]:
# testing
text  = 'menu?'
input_data = vectorizer.transform([text])
result = model.predict(input_data) # answer
print(lb.inverse_transform(result))

['menu']


In [74]:
# testing
text  = 'deliver for free?'
input_data = vectorizer.transform([text])
result = model.predict(input_data) # answer
print(lb.inverse_transform(result))

['delivery']


In [75]:
text ="show me the menu	"
input_data = vectorizer.transform([text])
result = model.predict(input_data) # answer
print(lb.inverse_transform(result))

['menu']


In [76]:
text ="are you available in lucknow?"
input_data = vectorizer.transform([text])
result = model.predict(input_data) # answer
print(lb.inverse_transform(result))

['address']


In [77]:
text ="combo offer of the week"
input_data = vectorizer.transform([text])
result = model.predict(input_data) # answer
print(lb.inverse_transform(result))

['combo']


In [78]:
text= 'are you open at 9am'
input_data = vectorizer.transform([text])
result = model.predict(input_data) # answer
ai_tag = lb.inverse_transform(result)[0]

# getting bot reply

In [92]:
rdf = pd.read_csv('bot_response_dataset.csv')

In [98]:
resultdf = rdf[rdf['tag']==tag] 

In [99]:
responses = resultdf.response.to_list()

In [100]:
import random

In [101]:
random.choice(responses)

'our address is 121/2312, hazratganj, lucknow'

In [84]:
import pickle

In [85]:
# classes
# binarzer
# model 
# vectorizer
model_data = {
    'binarizer': lb,
    'model' : model,
    'vectorizer':vectorizer,
    'classes':lb.classes_.tolist()
}

In [86]:
with open('model.pkl','wb') as f:
    pickle.dump(model_data, f)

# testing saved model

In [87]:
model_loaded_data = {}

with open('model.pkl','rb') as f:
    model_loaded_data = pickle.loads(f.read())

In [88]:
def predict_tag(txt='Hello world', vectorizer=None,
                model=None,binarizer=None,*args,**kwargs):
    input_vector = vectorizer.transform([txt])
    result = model.predict(input_vector)
    output_tag = lb.inverse_transform(result)
    return output_tag[0]

In [89]:
def get_bot_reply(predicted_tag):
    resultdf = rdf[rdf['tag']==predicted_tag] 
    responses = resultdf.response.to_list()
    return random.choice(responses)

In [104]:
text ="combo offer of the week"
tag = predict_tag(text,**model_loaded_data)
get_bot_reply(tag)

'buy 2 mexican pizza get 1 cold drink free, buy 5 large pizza combo at Rs. 2000 only'

In [106]:
text= 'are you available in lucknow?'
tag = predict_tag(text,**model_loaded_data)
get_bot_reply(tag)

'our address is 121/2312, hazratganj, lucknow'